apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: notes-pvc
  namespace: app
  labels:
    app: notes-api
    env: dev
    team: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi