apiVersion: v1
kind: Service
metadata:
  name: notes-api-svc
  namespace: app
  labels:
    app: notes-api
    env: dev
    team: backend
spec:
  selector:
    app: notes-api
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP