apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-pod-labels
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-required-labels
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - app
      validate:
        message: "Pods must have 'env' and 'team' labels."
        pattern:
          metadata:
            labels:
              env: "?*"
              team: "?*"